name: Executando testes com Python 3.8 e 3.9

on:
  pull_request:
    branches: [ main ]

env:
  POSTGRES_VOLUME_URL: /tmp/postgresql/data

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Configurando testes para versão ${{ matrix.python-version }} do Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalando dependências com Pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Levantando container
      run: |
        docker-compose up

    - name: Run Tests
      run: |
        pytest
