on:
  pull_request:
    branches: [ main ]

env:
  DB_USER: glico
  DB_PASSWORD: test
  DB_HOST: localhost
  DB_NAME: glicotest
  SEGREDO: TOPS3CRET
  POSTGRES_VOLUME_URL: /tmp/postgresql/data

jobs:
  build:
    name: Executando testes automatizados

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Configurando testes para versão ${{ matrix.python-version }} do Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalando dependências com Pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Levantando container
      run: |
        docker-compose -f "docker-compose.yml" up -d --build

    - name: Executando testes e verificando cobertura de testes
      run: |
        pytest --cov=libs/ --cov=contextos/ --cov-fail-under=90
